added 2nd method
4teenth/goit-nodejs pull request #1
Opened 2020-09-16 02:27 UTC by 4teenth

2020-09-16 10:25 UTC, odykyi commented on contacts.js
> +    fs.writeFile(this.contactsPath, JSON.stringify(result));
await fs.writeFile(this.contactsPath, JSON.stringify(result));

2020-09-16 10:25 UTC, odykyi commented on contacts.js
> +    fs.writeFile(this.contactsPath, contactsDataAsJSON);
await

2020-09-16 10:25 UTC, odykyi commented on contacts.js
> +// Method#2++++++++++++++++++++++++++++++++++++++
remove commented code

2020-09-16 10:25 UTC, odykyi commented on index.js
> +// Method#2++++++++++++++++++++++++++++++++++
remove commented

2020-09-16 10:25 UTC, odykyi requested changes
requested changes

2020-09-16 12:54 UTC, 4teenth commented
Got it! Fixed

2020-09-17 08:08 UTC, odykyi approved these changes

2020-09-17 08:08 UTC, merged